### ISSUE TITLE
App Image doesnt open, Ubuntu 22.04

### ISSUE THREAD

**Issue by oparada1988** [gdm-settings/gdm-settings#147]
appimage doesnt open, verified that libfuse2 is sintalled. Other images work with no issues

$ ./Login_Manager_Settings.AppImage 

** (process:20111): WARNING **: 17:31:32.978: Failed to load shared library 'libgdk_pixbuf-2.0.so.0' referenced by the typelib: libtiff.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/tmp/.mount_Login_zfJUfV/usr/bin/gdm-settings", line 27, in <module>
    from gdm_settings import Application
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gdm_settings/__init__.py", line 1, in <module>
    from .app import Application
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gdm_settings/app.py", line 10, in <module>
    from gi.repository import Adw, Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/overrides/GdkPixbuf.py", line 32, in <module>
    class Pixbuf(GdkPixbuf.Pixbuf):
  File "/tmp/.mount_Login_zfJUfV/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

**Comment by oparada1988** [comment]
Came to add that previous release works as intended

![Screenshot from 2023-02-07 17-45-04](https://user-images.githubusercontent.com/4031078/217384191-738fbcf9-4bdd-4259-9254-9743951c58f0.png)

**Comment by realmazharhussain** [comment]
Sorry for being late to reply. (Was a little busy)

The AppImage has more similar issues (see #137 for example). As far as I understand, the only way to properly fix this is to make the app buildable on older systems. I tried to do that with no luck. I'll try it again some (undecided) time in the future but that will probably not be soon.

However, since 2.x releases, I have changed a bit how the AppImage is created. So, maybe that will create an AppImage you can run! Try [this one](https://mega.nz/file/i4cSQDzA#E-gp_QoEeHWjhDf0hxTuYXJ1c-GboNNFeIf9jnJvwHo).

**Comment by tamsyn548** [comment]
> Sorry for being late to reply. (Was a little busy)
> 
> The AppImage has more similar issues (see #137 for example). As far as I understand, the only way to properly fix this is to make the app buildable on older systems. I tried to do that with no luck. I'll try it again some (undecided) time in the future but that will probably not be soon.
> 
> However, since 2.x releases, I have changed a bit how the AppImage is created. So, maybe that will create an AppImage you can run! Try [this one](https://mega.nz/file/i4cSQDzA#E-gp_QoEeHWjhDf0hxTuYXJ1c-GboNNFeIf9jnJvwHo).

I'm having the same issue, even with that new appimage.

![image](https://user-images.githubusercontent.com/111175305/233700332-59ce9f89-8f19-4ff8-ab96-f96adc3c73f0.png)

**Comment by alexmyczko** [comment]
No worries, future versions will have official package hopefully: https://ftp-master.debian.org/new/gdm-settings_3.1-1.html

**Comment by illtellyoulater** [comment]
OS: Pop!_OS 22.04 LTS x86_64
Kernel: 6.2.6-76060206-generic
DE: GNOME 42.5 

```
user@pop-os:~/Applications$  ./Login_Manager_Settings_5720f94cd698bfb44380183ad416ddef.AppImage 

/tmp/.mount_Login_GpzW4t/AppRun: line 8: 12858 Segmentation fault      (core dumped) gdm-settings "$@"
```

@realmazharhussain 

As you can see I also can't open the AppImage: 
I tried both the normal version and the one you provided in this thread, but they crash exactly the same way.

Moreover, for some reason, the AppImageLanucher won't let me uninstall them...
The flatpak version works, however I saw it has some limitations so I wanted to try the AppImage verison.
Is there something I can do?

**Comment by illtellyoulater** [comment]
@alexmyczko the html page you linked seems no longer available?

**Comment by alexmyczko** [comment]
because it is in debian now

**Comment by illtellyoulater** [comment]
@alexmyczko so it means now I can install it with apt?

**Comment by alexmyczko** [comment]
Yes if you run unstable (aka sid) with experimental added. Becaus it needs build-depends from experimental. After tomorrow and maybe a week or so it can land in unstable, a week later in testing.

**Comment by realmazharhussain** [comment]
@illtellyoulater Segmentation fault may be solved by the following AppImage.

https://mega.nz/file/rpMFBBha#yPiHxwtcw9W233-l_lw-px6ROaO2uSya2yo5Pa16wNI

**Comment by illtellyoulater** [comment]
@realmazharhussain still getting it:

```
alf@pop-os:~/Download$ ./gdm-settings.AppImage 

(AppImageLauncher:1297214): GLib-CRITICAL **: 18:51:54.489: g_file_test: assertion 'filename != NULL' failed
/tmp/.mount_gdm-setcu1yl/AppRun: line 8: 1297264 Segmentation fault      (core dumped) gdm-settings "$@"
```

**Comment by rk9qn3j** [comment]
I experience the same issue but on Fedora 38.

**Comment by schrodyn** [comment]
I'm getting the following error running the App Image on Ubuntu 22.04.

```
🦆 ./GDM_Settings.AppImage
/usr/bin/env: symbol lookup error: /tmp/.mount_GDM_SeOIzd2b/usr/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE
🦆 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

**Comment by realmazharhussain** [comment]
This issue is now being tracked in #209.
