### ISSUE TITLE
Cannot apply changes

### ISSUE THREAD

**Issue by plave0** [gdm-settings/gdm-settings#164]
### What happened?

The following error is printed in the terminal when trying to apply changes:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gdm_settings/lib/background_task.py", line 26, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gdm_settings/window.py", line 136, in on_apply_finished
    if self.apply_task.finish():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gdm_settings/lib/background_task.py", line 51, in finish
    raise value
  File "/usr/lib/python3.11/site-packages/gdm_settings/lib/background_task.py", line 36, in _thread_cb
    retval = self.function()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gdm_settings/settings.py", line 567, in apply_settings
    self.apply_shell_theme_settings()
  File "/usr/lib/python3.11/site-packages/gdm_settings/settings.py", line 350, in apply_shell_theme_settings
    compiled_file = gr_utils.compile(shelldir,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gdm_settings/gr_utils.py", line 99, in compile
    extract_default_theme(temp_theme_dir)
  File "/usr/lib/python3.11/site-packages/gdm_settings/gr_utils.py", line 67, in extract_default_theme
    resource_list = lib.get_stdout(["gresource", "list", env.HOST_ROOT + gresource_file]).splitlines()
                                                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

The program keeps running, but no changes are applied. 

### Expected behavior

Changes are applied successfully.

### To Reproduce

1. Install `gdm-settings`
2. Open `gdm-settings`, make some changes to the settings, and apply the changes
3. The changes are successfully saved
4. After logging out (from the popup dialogue after the settings have been successfully applied) and logging back in, open `gdm-settings` again
5. Try to make some other changes to the settings
6. Cannot apply changes anymore

### Application Version

3.1-2

### Format/Source

AUR (gdm-settings)

### Environment

- **OS**: Manjaro Linux
- **GNOME**: 44.1

**Comment by realmazharhussain** [comment]
Does reinstalling `gnome-shell` package fix the issue?
