### ISSUE TITLE
Crash on applying change in Ubuntu 23.10 with package build from source.

### ISSUE THREAD

**Issue by PandaJim** [gdm-settings/gdm-settings#200]
### What happened?

Compiled the latest v4.1 from the source code. It crashed every time clicking on "Apply" button.

Build dependency libraries: `Python 3.11.6, python3-gi 3.46.0, GTK 4.12.2, LibAdwaita 1.4.0`

Error output:

```
(gdm-settings:9919): Gtk-WARNING **: 00:06:55.967: Broken accounting of active state for widget 0x5050170(GtkColorChooserDialog)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gdms/utils.py", line 158, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/gui/window.py", line 138, in on_apply_finished
    if self.apply_task.finish():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/utils.py", line 183, in finish
    raise value
  File "/usr/lib/python3/dist-packages/gdms/utils.py", line 168, in _thread_cb
    retval = self.function()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/settings.py", line 567, in apply
    _gresource_apply()
  File "/usr/lib/python3/dist-packages/gdms/settings.py", line 365, in _gresource_apply
    compiled_file = gresource.compile(shelldir,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/gresource.py", line 190, in compile
    subprocess.run(['glib-compile-resources',
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'glib-compile-resources'
```

### Expected behavior

It should pop-up authentication dialog to input user password.

### To Reproduce

Compile v4.1 from source, launch it, change something, and click on "Apply".

### Application Version

4.1

### Format/Source

Source Code

### Environment

- **OS**: Ubuntu 23.10
- **GNOME**: 45

**Comment by PandaJim** [comment]
Great, it works!

I was trying to build the package into [PPA](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/gdm-settings), which of course include 'libglib2.0-dev' as build depends. But, don't know why it excludes the required dependency in the auto-generated `.deb` package.

It's easy to manually add it into dependency list, but usually it should be non '-dev' package. So, forgive me to ask again, does it need `libglid2.0-dev` indeed, or some other packages provided by glib2.0?

**Comment by realmazharhussain** [comment]
GDM Settings requires `glib-compile-resources` command during runtime. `glib-compile-resources` binary is part of `libglib2.0-dev` package. So, `libglib2.0-dev` is a runtime dependency of GDM Settings.

**Comment by PandaJim** [comment]
Got it. Thanks!
