### ISSUE TITLE
Python exception when applying "Energy" settings.

### ISSUE THREAD

**Issue by rastersoft** [gdm-settings/gdm-settings#211]
### What happened?

I did some changes in the "Energy" tab and pressed "Apply", but the program froze and this error was shown in the terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gdm_settings/lib/background_task.py", line 26, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdm_settings/window.py", line 136, in on_apply_finished
    if self.apply_task.finish():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdm_settings/lib/background_task.py", line 51, in finish
    raise value
  File "/usr/lib/python3/dist-packages/gdm_settings/lib/background_task.py", line 36, in _thread_cb
    retval = self.function()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdm_settings/settings.py", line 569, in apply_settings
    self.apply_shell_theme_settings()
  File "/usr/lib/python3/dist-packages/gdm_settings/settings.py", line 338, in apply_shell_theme_settings
    self.backup_default_shell_theme()
  File "/usr/lib/python3/dist-packages/gdm_settings/settings.py", line 322, in backup_default_shell_theme
    gr_utils.extract_default_theme(f'{env.TEMP_DIR}/default-pure')
  File "/usr/lib/python3/dist-packages/gdm_settings/gr_utils.py", line 67, in extract_default_theme
    resource_list = lib.get_stdout(["gresource", "list", env.HOST_ROOT + gresource_file]).splitlines()
                                                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

```

### Expected behavior

The "Energy" settings should have been updated.

### To Reproduce

Install "gdm-settings" as a .deb package and launch it. Go to the "Energy" tab and press "Apply".

### Application Version

3.3

### Format/Source

deb (from Ubuntu repositories)

### Environment

- **OS**: Ubuntu 23.10
- **GNOME**: 45

**Comment by rastersoft** [comment]
I added a `print` in the source code, and "resource_file" is None.

**Comment by realmazharhussain** [comment]
You probably tried out the deb after learning about it from [the OMG! Ubuntu post](https://www.omgubuntu.co.uk/2023/11/gdm-settings-customise-ubuntu-login-screen) where I mentioned that it existed. I'm sorry for that.

At the time, I did not realize that Ubuntu 23.10 shipped GDM Settings 3.3 alongside GNOME 45. However, GNOME 45 support was added in GDM Settings 4. So, it does not work on Ubuntu 23.10

Most probably, it exists in Ubuntu 23.10 just because of Debian. Debian Testing ships GDM Settings 3.3 alongside GNOME 44. So, the app should work there.

This should probably be reported to the Ubuntu developers.
