### ISSUE TITLE
Failed to apply shell theme with gnome 46, ubuntu 24.04

### ISSUE THREAD

**Issue by embabi2005** [gdm-settings/gdm-settings#240]
### What happened?

```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gdms/utils.py", line 158, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/gui/window.py", line 138, in on_apply_finished
    if self.apply_task.finish():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/utils.py", line 183, in finish
    raise value
  File "/usr/lib/python3/dist-packages/gdms/utils.py", line 168, in _thread_cb
    retval = self.function()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/settings.py", line 567, in apply
    _gresource_apply()
  File "/usr/lib/python3/dist-packages/gdms/settings.py", line 365, in _gresource_apply
    compiled_file = gresource.compile(shelldir,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gdms/gresource.py", line 190, in compile
    subprocess.run(['glib-compile-resources',
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'glib-compile-resources'
```

### Expected behavior

expected to apply the theme to the login screen

### To Reproduce

1. Open gdm-settings from terminal
2. Change shell theme and apply
3. Check the output in the terminal and logout to check (it is not applied)

### Application Version

4.3

### Format/Source

ubuntu repositories

### Environment

OS: Ubuntu 24.04
Gnome: 46

**Comment by realmazharhussain** [comment]
Looking at the Traceback and https://packages.ubuntu.com/noble/gdm-settings, I can see that this is an Ubuntu packaging bug. They are missing a dependency on `libglib2.0-dev`. Please, report it at https://launchpad.net/ubuntu/+source/gdm-settings/+bugs.
