### ISSUE TITLE
GDM Settings v4.4 won't open/start

### ISSUE THREAD

**Issue by Scotty-Trees** [gdm-settings/gdm-settings#259]
### What happened?

Latest flatpak update (from flathub) broke GDM Settings

### Expected behavior

Application should open, but instead it does not open when clicked. 

### To Reproduce

Here is the error message when trying to start GDM Settings from the terminal. Please let me know if you need any more detailed information, thanks. Btw, it may be relevant, but I am using an Acer laptop with hybrid Intel/Nvidia graphics running Nvidia 560.35.03. Didn't have any issues though, until recent flatpak updates.

```
scott@fedora:~$ flatpak run io.github.realmazharhussain.GdmSettings
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 23:32:03.824: Error 71 (Protocol error) dispatching to Wayland display.
scott@fedora:~$
```

### Application Version

4.4

### Format/Source

Flatpak

### Environment

- **OS**: Fedora 40
- **GNOME**:  45.6

Btw here is a quick system info:

```
# System Details Report
---

## Report details
- **Date generated:**                              2024-09-21 23:40:08

## Hardware Information:
- **Hardware Model:**                              Acer Aspire E5-576G
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i5-8250U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (KBL GT2)
- **Graphics 1:**                                  NVIDIA GeForce MX150
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            V1.32
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.10.10-200.fc40.x86_64
```

And here is my current flatpak runtimes installed:

```
scott@fedora:~$ flatpak list --runtime
Name                                                Application ID                                                    Version                                Branch                    Installation
Freedesktop Platform                                org.freedesktop.Platform                                          freedesktop-sdk-22.08.26               22.08                     system
Freedesktop Platform                                org.freedesktop.Platform                                                                                 23.08                     system
Freedesktop Platform                                org.freedesktop.Platform                                          freedesktop-sdk-24.08.1                24.08                     system
i386                                                org.freedesktop.Platform.Compat.i386                                                                     24.08                     system
Mesa                                                org.freedesktop.Platform.GL.default                               24.0.9                                 22.08                     system
Mesa (Extra)                                        org.freedesktop.Platform.GL.default                               24.0.9                                 22.08-extra               system
Mesa                                                org.freedesktop.Platform.GL.default                               24.2.1                                 23.08                     system
Mesa (Extra)                                        org.freedesktop.Platform.GL.default                               24.2.1                                 23.08-extra               system
Mesa                                                org.freedesktop.Platform.GL.default                               24.2.2                                 24.08                     system
Mesa (Extra)                                        org.freedesktop.Platform.GL.default                               24.2.2                                 24.08extra                system
nvidia-560-35-03                                    org.freedesktop.Platform.GL.nvidia-560-35-03                                                             1.4                       system
Mesa                                                org.freedesktop.Platform.GL32.default                             24.2.2                                 24.08                     system
nvidia-550-90-07                                    org.freedesktop.Platform.GL32.nvidia-550-90-07                                                           1.4                       system
nvidia-555-58-02                                    org.freedesktop.Platform.GL32.nvidia-555-58-02                                                           1.4                       system
nvidia-560-35-03                                    org.freedesktop.Platform.GL32.nvidia-560-35-03                                                           1.4                       system
Intel                                               org.freedesktop.Platform.VAAPI.Intel                                                                     22.08                     system
Intel                                               org.freedesktop.Platform.VAAPI.Intel                                                                     23.08                     system
Intel                                               org.freedesktop.Platform.VAAPI.Intel                                                                     24.08                     system
ffmpeg-full                                         org.freedesktop.Platform.ffmpeg-full                                                                     23.08                     system
FFmpeg extension with extra codecs                  org.freedesktop.Platform.ffmpeg-full                                                                     24.08                     system
openh264                                            org.freedesktop.Platform.openh264                                 2.1.0                                  2.2.0                     system
openh264                                            org.freedesktop.Platform.openh264                                 2.4.1                                  2.4.1                     system
GNOME Application Platform version 45               org.gnome.Platform                                                                                       45                        system
GNOME Application Platform version 46               org.gnome.Platform                                                                                       46                        system
GNOME Application Platform version 47               org.gnome.Platform                                                                                       47                        system
Adwaita dark GTK theme                              org.gtk.Gtk3theme.Adwaita-dark                                                                           3.22                      system
KDE Application Platform                            org.kde.Platform                                                                                         5.15-23.08                system
KDE Application Platform                            org.kde.Platform                                                                                         6.7                       system
QGnomePlatform                                      org.kde.PlatformTheme.QGnomePlatform                                                                     5.15-23.08                system
QAdwaitaDecorations                                 org.kde.WaylandDecoration.QAdwaitaDecorations                                                            5.15-23.08                system
QAdwaitaDecorations                                 org.kde.WaylandDecoration.QAdwaitaDecorations                                                            6.7                       system
QGnomePlatform-decoration                           org.kde.WaylandDecoration.QGnomePlatform-decoration                                                      5.15-23.08                system
scott@fedora:~$ 
```

**Comment by realmazharhussain** [comment]
1. Do other apps that use platform 47 (e.g. `org.gnome.Showtime`) run successfully?
2. Does running any of the below commands successfully launch the app?
   1. ```sh
      flatpak run --env=GSK_RENDERER=ngl io.github.realmazharhussain.GdmSettings
      ```
   2. ```sh
      flatpak run --env=GSK_RENDERER=gl io.github.realmazharhussain.GdmSettings
      ```
   3. ```sh
      flatpak run --env=GDK_BACKEND=x11 io.github.realmazharhussain.GdmSettings
      ```

**Comment by Scotty-Trees** [comment]
@realmazharhussain 

1. Other apps that use platform 47 do not launch as well. I have Showtime flatpak too and it no longer opens as well.
2.  i, ii, and iii all launch GDM Settings successfully. However option iv does not result in launching the app as observed here:

```
scott@fedora:~$ flatpak run --env=GDK_BACKEND=x11 io.github.realmazharhussain.GdmSettings

(gdm-settings:2): Gtk-CRITICAL **: 22:12:36.359: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gdm-settings:2): Gtk-CRITICAL **: 22:12:36.359: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed

(gdm-settings:2): Gtk-CRITICAL **: 22:12:36.360: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gdm-settings:2): Gtk-CRITICAL **: 22:12:36.360: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/gdms/gui/__init__.py", line 127, in do_activate
    self.window = GdmSettingsWindow(self)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/gdms/gui/window.py", line 59, in __init__
    super().__init__(**props)
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 505, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
scott@fedora:~$ 
```

I'm getting reports that it's a mesa issue perhaps, here's two relevant links. There's most likely nothing wrong with GDM Settings itself, so I believe you should be free to close this issue if you like. If I use Flatseal and turn off "Wayland windowing system" then I can get GDM Settings to launch as it just falls back to X11. Hoping upstream gets a fix out soon though. 

https://gitlab.freedesktop.org/mesa/mesa/-/issues/11723

https://bugzilla.redhat.com/show_bug.cgi?id=2301725
